### get all courses
GET http://localhost:3000/api/courses



### create new course
# @name createCourse
POST http://localhost:3000/api/courses
Content-Type: application/json 

{
  "title": "titletesdt3",
  "price": "302",
  "topics": [1]
}

### search by tittle
GET http://localhost:3000/api/courses?title=Priva

### ID
@id = {{createCourse.response.body.data.id}}

### get course by id
GET http://localhost:3000/api/courses/{{id}}

### Edit/modify course (PUT - recurso completo/objeto con estado final)
PUT http://localhost:3000/api/courses/2
Content-Type: application/json

{
  "id": 2,
  "tittle": "*sadsadas**",
  "price": "30",
  "topics": [1],
  "isActive": true
}

### POST a course
# @name createCourseToDelete
POST http://localhost:3000/api/courses
Content-Type: application/json 

{
  "tittle": "***",
  "price": "30",
"isActive": false,
"topics": [1]


}

###
@idToDelete = {{createCourseToDelete.response.body.data.id}}
### delete course
DELETE http://localhost:3000/api/courses/{{idToDelete}}


### Edit/modify course (PATCH - Modificaciones parciales/modificaciones incrementales)
PATCH http://localhost:3000/api/courses/2
Content-Type: application/json

{
  "tittle": "*sadsadas**",
  "price": 30,
  "isActive": false,
  "topics": [1,2],
  "isActive": true
}

