@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNvZsOtYSIsInN1cm5hbWUiOiJSYW3DrXJleiIsInBhc3N3b3JkIjoiIiwiZW1haWwiOiJzb2ZpYS5yYW1pcmV6QGxlYXJuc3BoZXJlLmNvbSIsImFkbWluIjpmYWxzZSwiaWF0IjoxNzY4MDg0OTA5LCJleHAiOjE3NjgxMTM3MDl9.rkJyQ70TjhxEj2ICHdy5IOVvxKYgJbb9uopt_pECCG4

### get all purchaseRecords
GET http://localhost:3000/api/coursePurchaseRecords?user=2
Authorization: Bearer {{token}}

### searchabyfechas purchaseRecords
GET http://localhost:3000/api/coursePurchaseRecords/courses?user=22&title=
Authorization: Bearer {{token}}

### check if user has purchased a course
GET http://localhost:3000/api/coursePurchaseRecords/check/1/2
Authorization: Bearer {{token}}

### create new purchaseRecord
# @name createPurchaseRecord
POST http://localhost:3000/api/coursePurchaseRecords
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user": 19,
  "course": 1
}
###ID
@id = {{createPurchaseRecord.response.body.data.id}} 
### get purchaseRecord by id
GET http://localhost:3000/api/coursePurchaseRecords/{{id}}
Authorization: Bearer {{token}}

### Edit/modify purchaseRecord (PUT - recurso completo/objeto con estado final)
PUT http://localhost:3000/api/courses/purchaseRecords/{{id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "montoTotal": 7000,
  "user": 1,
  "course": 1
}

### Post a purchaseRecord
# @name createPurchaseRecordToDelete
POST http://localhost:3000/api/courses/purchaseRecords
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "montoTotal": 2000,
  "course": 2
}

@idToDelete = {{createPurchaseRecordToDelete.response.body.data.id}}
### delete purchaseRecord
DELETE http://localhost:3000/api/courses/purchaseRecords/{{idToDelete}}
Authorization: Bearer {{token}}







Authorization: Bearer {{token}}

{
  "description": "PurchaseRecord 4"
}

### delete purchaseRecord
DELETE http://localhost:3000/api/courses/purchaseRecords/1
Authorization: Bearer {{token}}
}

### delete purchaseRecord
DELETE http://localhost:3000/api/courses/purchaseRecords/1