### LOGIN
POST http://localhost:3000/api/login
Content-Type: application/json
Credentials: include


{
  "email": "joaquinfds13@gmail.com",
  "password": "12345678"
}
###tokn
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "Goku1234"
}

###token
GET http://localhost:3000/api/login/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9hcXXDrW4gQ2FybG9zIiwic3VybmFtZSI6IkZlcm5hbmRleiBEYSBTaWx2YSIsInBhc3N3b3JkIjoiJGFyZ29uMmlkJHY9MTkkbT02NTUzNix0PTMscD00JEl1V0U4OWdXdTNnaWU3NkxFVXRSL1EkcTZoMENRY05WZGhmQVVoRWNraGpYdld1S0VzeVNUQVBKS1ZvalcvVEhvTSIsImVtYWlsIjoiam9hcXVpbmZkczEzQGdtYWlsLmNvbSIsImFkbWluIjpmYWxzZSwiaWF0IjoxNzQwNjExMTg4LCJleHAiOjE3NDA2Mzk5ODh9.y337ASNegWDFkAiUJAGApX9_LFEUIsQyDbo0fH17oLk
Content-Type: application/json
Credentials: include


###revoke token

POST http://localhost:3000/api/login/revoke-token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IkFkbWluIiwic3VybmFtZSI6IlVzZXIiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImFkbWluIjp0cnVlLCJpYXQiOjE3MzY0MjQzMDcsImV4cCI6MTczNjQ1MzEwN30.6lzPRy46mnJOlpEd7gxwN-c8wiNFUX6RPIrb_NuMdps"
}
###revoke token
